language: node_js
node_js:
  - "node"

before_install:
  - mysql -e 'CREATE DATABASE trektracker;'

before_script:
  - webpack -d

script:
  - npm test

cache:
  directories:
    - "node_modules"

services:
  - mysql

env:
  - NODE_ENV=test